# Generated by Django 4.0 on 2021-12-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
