# Generated by Django 4.0 on 2021-12-31 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0007_alter_userprofilemodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
